UniversityRegistrar/Models/Course.cs
using System.Collections.Generic;
using System;

namespace UniversityRegistrar.Models
{
  public class Course
  {
    public Course()
    {
      this.Students = new HashSet<CourseStudent>();
    }

    public int CourseId { get; set; }
    public string Name {get; set;}
    public string Number { get; set; }
    public virtual ICollection<CourseStudent> Students {get; set;}
  }
}

UniversityRegistrar/Models/CourseStudent.cs
namespace UniversityRegistrar.Models
{
  public class CourseStudent
  {
    public int CourseStudentId {get; set;}
    public int StudentId {get; set;}
    public int CourseId {get; set;}
    
    public Student Student {get; set;}
    
    public Course Course {get; set;}
  }
}

UniversityRegistrar/Models/Department.cs
using System.Collections.Generic;
using System;

namespace UniversityRegistrar.Models
{
  public class Department
  {
    public Department()
    {
      this.Students = new HashSet<Student>();
      this.Courses = new HashSet<Course>();
    }

    public int CourseId { get; set; }
    public string Name {get; set;}
    public string Number { get; set; }
    public virtual ICollection<CourseStudent> Students {get; set;}
  }
}

UniversityRegistrar/Models/DesignTimeDBContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace UniversityRegistrar.Models
{
  public class UniversityRegistrarContextFactory : IDesignTimeDbContextFactory<UniversityRegistrarContext>
  {

    UniversityRegistrarContext IDesignTimeDbContextFactory<UniversityRegistrarContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<UniversityRegistrarContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new UniversityRegistrarContext(builder.Options);
    }
  }
}

UniversityRegistrar/Models/Student.cs
using System.Collections.Generic;
using System;

namespace UniversityRegistrar.Models
{
  public class Student
  {
    public Student()
    {
      this.Courses = new HashSet<CourseStudent>();
    }
    
    public int StudentId {get; set;}
    
    public string Name {get; set;}

    public string DateEnrolled { get; set;}
    
    public int CourseId {get; set;}
    
    public ICollection<CourseStudent> Courses {get;}
  }
}

UniversityRegistrar/Models/UniversityRegistrarContext.cs
using Microsoft.EntityFrameworkCore;

namespace UniversityRegistrar.Models
{
  public class UniversityRegistrarContext : DbContext
    {       
    public virtual DbSet<Course> Courses { get; set; }
    public DbSet<Student> Students{ get; set; }
    public DbSet<CourseStudent> CourseStudent { get; set; }

    public UniversityRegistrarContext(DbContextOptions options) : base(options) { }
    }
}

UniversityRegistrar/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using UniversityRegistrar.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace UniversityRegistrar.Controllers
{
  public class CoursesController : Controller
  {
    private readonly UniversityRegistrarContext _db;

    public CoursesController(UniversityRegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Course> model = _db.Courses.ToList();
      return View(model);
    }     

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Course course)
    {
      _db.Courses.Add(course);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      // Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      // thisCuisine.Restaurants = _db.Restaurants.Where(restaurant => restaurant.CuisineId == id).ToList();
      var thisCourse = _db.Courses
        .Include(course => course.Students)
        .ThenInclude(join => join.Student)
        .FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    public ActionResult Edit(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    public ActionResult Edit(Course course)
    {
      _db.Entry(course).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      _db.Courses.Remove(thisCourse);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Search(string search)
    {
      List<Course> model = _db.Courses.Where(course => course.Name.Contains(search)).ToList();
      return View(model);
    }
  }
}

UniversityRegistrar/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace UniversityRegistrar.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

UniversityRegistrar/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using UniversityRegistrar.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace UniversityRegistrar.Controllers
{
  public class StudentsController : Controller
  {
    private readonly UniversityRegistrarContext _db;

    public StudentsController(UniversityRegistrarContext db)
    {
      _db = db;
    }
    
    public ActionResult Index()
    {
      return View(_db.Students.ToList());
    }
    
    public ActionResult Details(int id)
    {
      var thisStudent = _db.Students
        .Include(student => student.Courses)
        .ThenInclude(join => join.Course)
        .FirstOrDefault(student => student.StudentId == id);
      return View(thisStudent);
    }
    public ActionResult Create()
    {
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "Name");
      return View();
    }
        [HttpPost]
    public ActionResult Create(Student student, int CourseId)
    {
      _db.Students.Add(student);
      if (CourseId != 0)
      {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    
    }
    public ActionResult Edit(int id)
    {
        var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
        ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "Name");

        return View(thisStudent);
    }

    [HttpPost]
    public ActionResult Edit(Student student, int CourseId)
    {
      if (CourseId != 0)
      {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
      }
      
      _db.Entry(student).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddCourse(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "Name");
      return View(thisStudent);
    }
    [HttpPost]
    public ActionResult AddCourse(Student student, int CourseId)
    {
        if (CourseId != 0)
        {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
        }
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
        var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
        return View(thisStudent);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      _db.Students.Remove(thisStudent);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteCourse(int joinId)
    {
      var joinEntry = _db.CourseStudent.FirstOrDefault(entry => entry.CourseStudentId == joinId);
      _db.CourseStudent.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

UniversityRegistrar/Views/Courses/Create.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Course

<div class="row">
  <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
    <div class="card bg-warning my-5">
      <div class="card-body">
        <h4>Add a new Course</h4>
        @using (Html.BeginForm())
        {
          <div class="form-group">
            @Html.LabelFor(model => model.Name)
            @Html.TextBoxFor(model => model.Name, new{ @class="form-control"})
          </div>  
          <div class="form-group">
            @Html.LabelFor(model => model.Number)
            @Html.TextBoxFor(model => model.Number, new{ @class="form-control"})
          </div>  
          
          <button type="submit" class="btn btn-light">Add</button>
        }
        <div>
        <p>@Html.ActionLink("Show all Courses", "Index")</p>
      </div>
    </div>
  </div>
</div>

UniversityRegistrar/Views/Courses/Delete.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Course
<div class="row">
  <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
    <div class="card bg-warning my-5">
      <div class="card-body">
        <h2>Are you sure you want to delete @Html.DisplayFor(model => model.Name)?</h2>
        @using (Html.BeginForm())
        {
            <button class="btn btn-light" type="submit">YES</button>
        }
        <br>
        @Html.ActionLink("Back to List", "Index")
      </div>
    </div>
  </div>
</div>

UniversityRegistrar/Views/Courses/Details.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models
@model UniversityRegistrar.Models.Course
<div class="row">
  <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
    <div class="card bg-warning my-5">
      <div class="card-body">
        <h2>Students in </h2>
        <h2>@Html.DisplayFor(model => model.Name)</h2>
        <hr />

        @if (Model.Students.Count == 0)
        {
          <p>There are no Students in this Course.</p>
        }
        else 
        {
          <h4>Students in this Course:</h4>
          <ul>
          @foreach (var join in Model.Students)
          {
              <li>@join.Student.Name</li>
          }
          </ul>
        }

        <hr/>

        <p>@Html.ActionLink("Back to List", "Index")</p>
        <p>@Html.ActionLink("Edit Course", "Edit", new { id = Model.CourseId })</p>
        <p>@Html.ActionLink("Delete Course", "Delete", new { id = Model.CourseId })</p>
      </div>
    </div>
  </div>
</div>

UniversityRegistrar/Views/Courses/Edit.cshtml
@{
  Layout = "_Layout";
}
@model UniversityRegistrar.Models.Course
<h2>Edit</h2>

<h4>Edit this Course: @Html.DisplayFor(model => model.Name)</h4>

@using (@Html.BeginForm())
{
  @Html.HiddenFor(model => model.CourseId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  @Html.LabelFor(model => model.Number)
  @Html.EditorFor(model => model.Number)

  <input type = "submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

UniversityRegistrar/Views/Courses/Index.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models;
@using System.Collections.Generic;
@model List<UniversityRegistrar.Models.Course>;

  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card bg-warning my-5">
        <div class="card-body">
          <h1>Courses</h1>
          <hr>
          @if (@Model.Count == 0)
          {
            <h3>No Courses have been added yet!</h3>
          } 
            @foreach(Course course in Model)
            {
                <p>@Html.ActionLink($"{course.Name}", "Details", new { id = course.CourseId })</p>
            }

            <hr/>

            <p>@Html.ActionLink("Add new Course", "Create")</p>

            <p>@Html.ActionLink("Home", "Index", "Home")</p>

        </div>  
      </div>
    </div>
  </div>        

UniversityRegistrar/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<div class="jumbotron">
  <h1 class=splash-page-header>Welcome to the University Registrar!</h1>
</div>


<div class="button-parent">
  <div class="button-group">
  
  <div class="form-group w-50" id="search">
  @using (Html.BeginForm("Search","Courses")) {
  <input type="text" name="search" class="form-control form-control-lg"/>
  <br>
  <input type="submit" value="Search Courses" class="btn btn-success my-2 my-sm-0">
  }
</div>
    <button class="btn btn-warning">@Html.ActionLink("See all Courses", "Index", "Courses")</button>
    <button class="btn btn-warning">@Html.ActionLink("Add a new Course", "Create", "Courses")</button>
    <button class="btn btn-warning">@Html.ActionLink("See all Students", "Index", "Students")</button>
    <button class="btn btn-warning">@Html.ActionLink("Add a new Student", "Create", "Students")</button>
  </div>
</div>

UniversityRegistrar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<body>
  <head>
    <meta charset="utf-8">
    <title>University Registrar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Pacifico&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">
        <img src="../img/locator-logo.png" width="30" height="30">University Registrar
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/Courses">Courses</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/Students">Students</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container-fluid">
      @RenderBody()
    </div>
    @Html.Partial("Footer")
  </body>
</body>

UniversityRegistrar/Views/Students/AddCourse.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student

<h4> Add a course for this student: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StudentId)
  
  @Html.Label("Select course")
  @Html.DropDownList("CourseId")
  
  <input type="submit" value="save">
}

UniversityRegistrar/Views/Students/Create.cshtml
@{
  Layout = "_Layout";
}
@model UniversityRegistrar.Models.Student

<h4>Add a new Student</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    @Html.LabelFor(model => model.DateEnrolled)
    @Html.TextBoxFor(model => model.DateEnrolled, "{0:dd/MM/yyyy}")
    @Html.Label("Select a Course")
    @Html.DropDownList("CourseId")
    <input type="submit" value="Add a new student" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all students", "Index")</p>

UniversityRegistrar/Views/Students/Delete.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student
<div class="row">
  <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
    <div class="card bg-warning my-5">
      <div class="card-body">
        <h2>Are you sure you want to delete @Html.DisplayFor(model => model.Name)</h2>
        @using (Html.BeginForm())
        {
            <button class="btn btn-light" type="submit">YES</button>
        }
        @Html.ActionLink("Back to List", "Index")
      </div>
      
    </div>
  </div>
</div>

UniversityRegistrar/Views/Students/Details.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models
@model UniversityRegistrar.Models.Student
<div class="row">
  <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
    <div class="card bg-warning my-5">
      <div class="card-body">
        <h2>Student Details</h2>
        <h2>@Html.DisplayFor(model => model.Name)</h2>
        <hr />

        <p>@Html.DisplayNameFor(model => model.DateEnrolled): @Html.DisplayFor(model => model.DateEnrolled)<p>
        @* <h4>@Html.DisplayNameFor(model => model.Cui): @Html.DisplayFor(model => model.Category)</h4> *@
        <p>@Html.DisplayNameFor(model => model.StudentId): @Html.DisplayFor(model => model.StudentId)</p>

        @if(@Model.Courses.Count == 0)
        {
          <p>This Student is not enrolled in any Courses</p>
        }
        else{
          <h4>This Student's Courses</h4>
            <ul>
              @foreach(var join in Model.Courses)
              {
                <li>@join.Course.Name</li>
                @using (Html.BeginForm("DeleteCourse", "Students"))
                {
                  @Html.Hidden("joinId", @join.CourseStudentId)
                  <input type="submit" value="Delete"/>
                }
              }
            </ul>
        }
        <hr/>
        <p>@Html.ActionLink("Back to List", "Index")</p>
        <p>@Html.ActionLink("Edit this Student", "Edit", new { id = Model.StudentId })</p>
        <p>@Html.ActionLink("Delete This Student", "Delete", new { id = Model.StudentId })</p>
        <p>@Html.ActionLink("Add a Course", "AddCourse", new { id = Model.StudentId })</p>

      </div>
    </div>
  </div>
</div>

UniversityRegistrar/Views/Students/Edit.cshtml
@{
  Layout = "_Layout";
}
@model UniversityRegistrar.Models.Student
<h2>Edit</h2>

<h4>Edit this Student: @Html.DisplayFor(model => model.Name)</h4>

@using (@Html.BeginForm())
{
  @Html.HiddenFor(model => model.StudentId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  @Html.LabelFor(model => model.DateEnrolled)
  @Html.EditorFor(model => model.DateEnrolled)
  @Html.LabelFor(model => model.CourseId)
  @Html.EditorFor(model => model.CourseId)
  @Html.Label("Select Course")
  @Html.DropDownList("CourseId")

  <input type = "submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

UniversityRegistrar/Views/Students/Index.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models;
@using System.Collections.Generic;
@model List<UniversityRegistrar.Models.Student>;


  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card bg-warning my-5">
        <div class="card-body">
          <h1>Students</h1>
          <hr>
          @if (@Model.Count == 0)
          {
            <h3>No Students have been added yet!</h3>
          } 
          <ul>
            @foreach(Student student in Model)
            {
                <li>@Html.ActionLink($"{student.Name}", "Details", new { id = student.StudentId }) </li>
            }

            <hr/>

            <p>@Html.ActionLink("Add new Student", "Create")</p>

            <p>@Html.ActionLink("Home", "Index", "Home")</p>
          </ul>
        </div>
      </div>
    </div>
  </div>        